version: '3'
services:
  db: 
    image: postgres
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: mak
      POSTGRES_DB: school_db
    ports: 
      - 13001:5432
  app: 
    image: express-app
    ports:
      - 13000:3000